# travis.yml
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
